package main

import (
	"io"
	"log"
	"net/http"
	"time"
)

// Editor renders the legislation drafting editor at /editor
func (a *App) Editor(w http.ResponseWriter, r *http.Request) {
	T := Printer(r.Context())
	templateName := "editor.html"
	t := newTemplate(a.templateFS, templateName)
	w.Header().Set("content-type", "text/html")
	a.addExpireHeaders(w, time.Minute*5)
	type Page struct {
		Page  string
		Title string
	}
	body := Page{
		Page:  "editor",
		Title: T.Sprintf("Legislation Editor"),
	}
	err := t.ExecuteTemplate(w, templateName, body)
	if err != nil {
		log.Print(err)
		http.Error(w, "Internal Server Error", 500)
		return
	}
}

// EditorLawCorpus serves the corpus of existing law available to the editor.
//
// The response shape is the editor's contract with the eventual legislation
// API; today it is backed by a fixture generated by
// scripts/extract_law_fixture.py. See PLAN.md section 9.
func (a *App) EditorLawCorpus(w http.ResponseWriter, r *http.Request) {
	f, err := a.staticFS.Open("static/editor/law_fixture.json")
	if err != nil {
		log.Printf("editor corpus: %s", err)
		http.Error(w, "Internal Server Error", 500)
		return
	}
	defer f.Close()
	w.Header().Set("content-type", "application/json")
	a.addExpireHeaders(w, time.Minute*15)
	if _, err := io.Copy(w, f); err != nil {
		log.Printf("editor corpus: %s", err)
	}
}
